version: '3'

services:
  mongo:
    image: mvertes/alpine-mongo
  prizr:
    depends_on:
      - mongo
    image: openjdk:7-alpine
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    working_dir: /app
    entrypoint:
      - java
      - -jar
      - target/Prizr-webapp-jar-with-dependencies.jar
      - mongo
      - prizr
      - "8080"
