package fi.floweb
 
import fi.floweb.prizr.beans.*;

rule "Category, country and location code determine which pricemultiplier should be used"
	when 
		$preq : PricingRequest()
		$pres : PricingResponse(pricingDone == false)
		$multiplier : MultiplierBase(appliesToLocation == $preq.locationCode && 
									countryCode == $preq.countryCode &&
									appliesToCategory == $preq.itemCategoryCode &&
									appliesToShopCode == $preq.shopCode)
	then
		double newPrice = $preq.getSalesPrice()*$preq.getCommission()*$multiplier.getMultiplier();
		double transit = $preq.getItemStandardCost()+($multiplier.getIncludesFreight() / $preq.getItemUnitCC());
		transit = transit * $multiplier.getFreightMultiplier();
		double finalPrice = newPrice + transit; 
		$pres.setPrice(finalPrice);
		$pres.setPricingDone(true);
		update( $pres )
end